name: Check Saldo Pagaqui

on:
  schedule:
    # Corre a las 7, 8, 9, ..., 21 horas (7am a 9pm) todos los días
    - cron: '0 13-03 * * *' # UTC: 13 (7am) a 3 (9pm) siguiente día
  workflow_dispatch:

jobs:
  check-saldo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright twilio
        playwright install chromium

    - name: Run saldo checker
      env:
        PAGAAQUI_USER: ${{ secrets.PAGAAQUI_USER }}
        PAGAAQUI_PASS: ${{ secrets.PAGAAQUI_PASS }}
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      run: python main.py
