name: Cheque Saldo Pagaqui

on:
  schedule:
    - cron: '0 13-21 * * *' # De 7am a 3pm hora MX (ajusta si horario de verano cambia)
  workflow_dispatch:

jobs:
  check-saldo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-attempts: 3  # <-- ¡Esto activa los reintentos automáticos!
    steps:
      - name: Repositorio de pago
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Ejecutar script de saldo
        env:
          PAGAQUI_USER: ${{ secrets.PAGAQUI_USER }}
          PAGAQUI_PASS: ${{ secrets.PAGAQUI_PASS }}
          RECARGAQUI_USER: ${{ secrets.RECARGAQUI_USER }}
          RECARGAQUI_PASS: ${{ secrets.RECARGAQUI_PASS }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python main.py
