name: Cheque Saldo Pagaqui

on:
  schedule:
    - cron: '0 13-21 * * *'  # Corre cada hora de 7am a 3pm MX (ajusta si cambia el horario)
  workflow_dispatch:

jobs:
  check-saldo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Ejecutar script de saldo
        env:
          PAGAQUI_USER: ${{ secrets.PAGAQUI_USER }}
          PAGAQUI_PASS: ${{ secrets.PAGAQUI_PASS }}
          RECARGAQUI_USER: ${{ secrets.RECARGAQUI_USER }}
          RECARGAQUI_PASS: ${{ secrets.RECARGAQUI_PASS }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python main.py
