name: Check Saldo Pagaqui

on:
  schedule:
    - cron: '*/2 * * * *'  # Cada 2 minutos para pruebas
  workflow_dispatch:      # Permite ejecutarlo manualmente

jobs:
  check-saldo:
    runs-on: ubuntu-latest

    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      PAGAQUI_USER: ${{ secrets.PAGAQUI_USER }}
      PAGAQUI_PASS: ${{ secrets.PAGAQUI_PASS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright twilio
          playwright install chromium

      - name: Run saldo check
        run: |
          python main.py
