name: Prueba cada 2 minutos

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  consultar-saldo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install playwright twilio
          playwright install chromium

      - name: Ejecuta script principal
        env:
          PAGAQUI_USER: ${{ secrets.PAGAQUI_USER }}
          PAGAQUI_PASS: ${{ secrets.PAGAQUI_PASS }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python main.py
